[package]
name = "omnical"
version = "0.2.0"
edition = "2021"
description = "displays a calendar of different kinds"
license = "MIT"
repository = "https://github.com/hanwentao/omnical/"
readme = "README.md"

[dependencies]
chrono = "0.4.33"
